name: Update Holidays

on:
  schedule:
    - cron: "0 0 * * *" # run daily at midnight UTC
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Fetch and Filter Holidays
        run: |
          mkdir -p data
          curl -s https://hari-libur-api.vercel.app/api > all.json
          node -e "const fs=require('fs');const data=JSON.parse(fs.readFileSync('all.json','utf8'));const filtered=data.filter(d=>d.is_national_holiday===true);fs.writeFileSync('data/holidays.json', JSON.stringify(filtered,null,2));"

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/holidays.json
          git commit -m "Update national holidays.json" || echo "No changes to commit"
          git push
